export const TRANSLATIONS = {
    en_US: {
      Username: 'Username',
      Password: 'Password',
      Forgot_password: 'Forgot password?',
      Sign_in: 'Sign in',
      Search:'Search',
      Dashboard:'Dashboard',
      Users: 'Users',
      Save: 'Save',
      Settings: 'Settings',
      Buy_Credits: 'Buy Credits',
      Get_File: 'Get Files',
      Credits: 'Credits',
      Available_Credits: 'Available Credits',
      Number_of_Credits: 'Number of Credits',
      Credits_Amount: 'Credits Amount',
      Buy: 'Buy',
      Upload_File: 'Upload File',
      CreditsNeededToBuyFile: 'Credits Needed To Buy File: ',
      Approve: 'Approve',
      Key: 'Key',
      Value:'Value',
      Choose_File: "Choose File",
      Add_Settings: 'Add Settings',
      PricePerCredit: 'PricePerCredit',
      CreditPerTimber: 'Creditsperhout',
      CreditPerPlate: 'CreditPerPlate',
      Price_per_credit: 'Price per credit',
      Timber_tag: 'Timber tag',
      Plate_tag: 'Plate tag',
      Add_User: 'Add User',
      FirstName: 'FirstName',
      LastName: 'LastName',
      Email: 'Email',
      Active: 'Active',
      State: 'State',
      View_User: 'View User',
      Edit_User: 'Edit User',
      UserName: 'UserName',
      Roles: 'Roles',
      ConfirmPassword: 'ConfirmPassword',
      Credit_History: 'Credit History',
      CreateDate: 'CreateDate',
      Creditsreductedoradded: 'Creditsreductedoradded',
      Download_Link: 'Download link',
      View_Link: 'View Link',
      Success: 'Success!',
      Expired: 'Expired!',
      Cancelled: 'Cancelled!',
      Failure: 'Failure!',
      Success_m: 'The payment is succesful!',
      Expired_m: 'The payment is expired!',
      Failure_m: 'The payment has failed!',
      Cancelled_m: 'The payment has been cancelled!'
    },
    nl_BE: {
      Username: 'Gebruikersnaam',
      Password: 'Wachtwoord',
      Forgot_password: 'Wachtwoord vergeten?',
      Sign_in: 'Aanmelden',
      Search:'Zoeken',
      Dashboard:'Dashboard',
      Users: 'Gebruikers',
      Save: 'Obslaan',
      Settings: 'Instellingen',
      Buy_Credits: 'Koop tegoed',
      Get_File: 'Bestanden ophalen',
      Credits: 'Credits',
      Available_Credits: 'Beschikbare credits',
      Number_of_Credits: 'Aantal credits',
      Credits_Amount: 'Credits Bedrag',
      Buy: 'Kopen',
      Upload_File: 'Upload bestand',
      CreditsNeededToBuyFile: 'BenodigdeCreditsOmEenBestandTeKopen: ',
      Approve: 'Goedkeuren',
      Key: 'Sleutel',
      Value:'Waarde',
      Choose_File: 'Kies bestand',
      Add_Settings: 'Instellingen toevoegen',
      PricePerCredit: 'PrijsPerTegoed',
      CreditPerTimber: 'Creditsperhout',
      CreditPerPlate: 'CreditPerPlaat',
      Price_per_credit: 'Prijs per tegoed',
      Timber_tag: 'Hout tag',
      Plate_tag: 'Plaat tag',
      Add_User: 'Voeg gebruiker toe',
      FirstName: 'Voornaam',
      LastName: 'Achternaam',
      Email: 'Email',
      Active: 'Actief',
      State: 'Staat',
      View_User: 'Bekijk Gebruiker',
      Edit_User: 'Bewerk Gebruiker',
      UserName: 'Gebruikersnaam',
      Roles: 'Rollen',
      ConfirmPassword: 'Bevestig Wachtwoord',
      Credit_History: 'Krediet geschiedenis',
      CreateDate: 'GemaaktDate',
      Creditsreductedoradded: 'Creditsverlaagdoftoegevoegd',
      Download_Link: 'Download Link',
      View_Link: 'Bekijk link',
      Success: 'Succes!',
      Expired: 'Vervallen!',
      Cancelled: 'Geannuleerd!',
      Failure: 'Mislukking!',
      Success_m: 'De betaling is geslaagd!',
      Expired_m: 'De betaling is verlopen!',
      Failure_m: 'De betaling is mislukt!',
      Cancelled_m: 'De betaling is geannuleerd!'
    }
  };